# Generated by Django 5.1.15 on 2026-07-05 20:15

from django.db import migrations, models


def set_discount_duration_30s(apps, schema_editor):
    """Mavjud sozlamalar qatorini 30 soniyaga o'tkazamiz (eski 180 -> 30)."""
    BotSettings = apps.get_model('core', 'BotSettings')
    # Faqat eski default (180)da qolganlarni yangilaymiz; admin qo'lda boshqa qiymat
    # qo'ygan bo'lsa (masalan 60), tegmaymiz.
    BotSettings.objects.filter(discount_duration=180).update(discount_duration=30)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_message_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='discount_duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Chegirma muddati (sekund)'),
        ),
        migrations.RunPython(set_discount_duration_30s, noop_reverse),
    ]
