# Generated by Django 5.1.15 on 2026-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_country_savedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram File ID'),
        ),
    ]
