# Generated by Django 5.1.15 on 2026-07-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_file_id'),
        ('users', '0005_user_flash_sale_started_user_trial_flash_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Yoqtirishlar soni'),
        ),
        migrations.CreateModel(
            name='MovieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="So'ralgan kino")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', "Qo'shildi"), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'ralgan vaqt")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_requests', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Kino so'rovi",
                'verbose_name_plural': "Kino so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yoqtirilgan vaqt')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='movies.movie', verbose_name='Kino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yoqtirish',
                'verbose_name_plural': 'Yoqtirishlar',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name="Ko'rilgan vaqt")),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movies.movie', verbose_name='Kino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Ko'rish tarixi",
                'verbose_name_plural': "Ko'rish tarixi",
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
