# Generated by Django 5.1.15 on 2026-07-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_premium_expiry_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flash_sale_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Flash sale boshlangan'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_flash_sent',
            field=models.BooleanField(default=False, verbose_name='Trial flash yuborilgan'),
        ),
    ]
