# Generated by Django 5.1.15 on 2026-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_flash_sale_started_user_trial_flash_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_movie_message_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Oxirgi kino xabarlari'),
        ),
    ]
