# Generated by Django 5.1.15 on 2026-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_add_channel_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('telegram_channel', 'Telegram kanal'), ('telegram_group', 'Telegram guruh'), ('telegram_bot', 'Telegram bot'), ('instagram', 'Instagram'), ('external', 'Tashqi platforma')], default='telegram_channel', max_length=20, verbose_name='Turi'),
        ),
    ]
