# Generated by Django 5.1.15 on 2026-07-05 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_channel_type'),
        ('users', '0004_user_premium_expiry_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="So'rov vaqti")),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='channels.channel', verbose_name='Kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_join_requests', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Kanalga qo'shilish so'rovi",
                'verbose_name_plural': "Kanalga qo'shilish so'rovlari",
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
